# version: '3.14'
services:
  mariadb:
    build:
      dockerfile: mariadb.dockerfile
      context: ./requirements/mariadb/
    image: mariadb:inception
    # container name to name a container oviously
    container_name: inception_mariadb
    # just to name the image
    pull_policy: never 
    networks:
      - inception_network


  nginx:
    build:
      dockerfile: nginx.dockerfile
      context: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    pull_policy: never
    ports:
      - 443:443
    networks:
        - inception_network

  wordpress:
    build:
      dockerfile: wordpress.dockerfile
      context: ./requirements/wordpress/
    image: wordpress:inception
    pull_policy: never
    networks:
        - inception_network


networks:
  inception_network:
    name: something
