server {
  listen 443 ssl
  server_name my_first_interaction;
  ssl_certificate /put/here/certificate;
  ssl_certificate_key /put/here/certificate/key;
  ssl_protocols TLSv1.2 TLSv1.3;
   # s 
}

# server {
#   listen 80;
#   return 302 https:;
# }
