server {
  root /;
  listen 443 ssl;
  server_name my_first_interaction;
  ssl_certificate_key /etc/nginx/ssl/private/server.key;
  ssl_certificate /etc/nginx/ssl/certs/certificate.pem;
  ssl_protocols TLSv1.2 TLSv1.3;

  location ~ \.php$  {
    root /wordpress/;
    include snippets/fastcgi-php.conf;
    fastcgi_pass wordpress:9000;
  }
}

server {
  listen 80;
  return 302 https:$host$uri;
}
