services:
  ftp-server:
    build:
      dockerfile: ftp-server.dockerfile
      context: .
    pull_policy: never
    image: ftp-server:inception
    container_name: inception_ftp-server
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
   # networks:
     #   - inception_network
